[book]
authors = ["Jonas Kruckenberg"]
language = "en"
src = "book"

[build]
build-dir = "dist"
extra-watch-dirs = ["../transformers"]

[output.html]
additional-css = ["workshop.css", "wasm/frontend_bg.wasm"]
additional-js = ["workshop.js", "wasm/frontend.js"]
hash-files = false

[output.html.playground]
editable = true
