[build]
target = "index.html"
dist = "dist"

[serve.headers]
# see ./_headers for more documentation
"cross-origin-embedder-policy"= "require-corp"
"cross-origin-opener-policy"= "same-origin"
"cross-origin-resource-policy"= "same-site"
