[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
photon.workspace = true
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
transformers.workspace = true
